### ISSUE TITLE
Error when switching between header line

### ISSUE THREAD

**Issue by rgrinberg** [jeetsukumaran/vim-buffersaurus#7]
This only occurs if I navigate through a "header" line. I.e. one that contains a file name. Screenshot of error:

https://www.evernote.com/shard/s417/sh/433efa14-a47b-49d1-bb35-6cc2f7b06c4d/937d42ccd81772dd414e00bc6e30d47d

**Comment by jeetsukumaran** [comment]
I cannot replicate this error. How exactly do you navigate through the header line? Using the `j`/`k` keys? Or `<SPACE>`? Or `<C-N>`/`<C-P>`?

**Comment by rgrinberg** [comment]
This is using `j` and `k`

**Comment by jeetsukumaran** [comment]
This error does not appear to be in Buffersaurus. The problem is with the function "Highlight_Matching_Pair", which is in some other plugin that you have installed. I do not have any idea what the plugin is, or what the problem is, but I suspect that it is getting confused by, e.g., the ``:::`` characters or something.

**Comment by rgrinberg** [comment]
That's what I thought initially as well but in fact this function comes with Vim: https://github.com/b4winckler/vim/blob/master/runtime/plugin/matchparen.vim#L39

**Comment by jeetsukumaran** [comment]
Hmmm. Could you do a grep of your Vim directory and see where else that function might occur?

I still think that the problem might lie with an other plugin because I cannot seem to replicate it on any of my installations. 

I have revised my suspicion as to the reason for the problem, wherever it might be found: another plugin is trying to use ``3match``. I will see if I can find a work-around.

**Comment by rgrinberg** [comment]
I've grepped through all my plugins again and the only one (apart from buffersaurus) that uses 3match is https://github.com/tomtom/tlib_vim/blob/master/autoload/tlib/buffer.vim#L204

Unfortunately, getting rid of it doesn't seem to help.

**Comment by jeetsukumaran** [comment]
OK, just pushed a fix that avoids using ``3match``. Let me know if it works.

**Comment by rgrinberg** [comment]
:100:
